package ServerObjectInterfaceApp;


/**
* ServerObjectInterfaceApp/ServerObjectInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerObjectInterface.idl
* Tuesday, April 9, 2024 10:22:40 o'clock AM EDT
*/

public interface ServerObjectInterfaceOperations 
{

  /**
          * Only admin
          */
  String addAppointment (String userID, String appointmentID, String appointmentType, int bookingCapacity);
  String removeAppointment (String userID, String appointmentID, String appointmentType);
  String listAppointmentAvailability (String userID, String appointmentType);

  /**
          * Both admin and patient
          */
  String bookAppointment (String patientID, String appointmentID, String appointmentType);
  String getAppointmentSchedule (String patientID);
  String cancelAppointment (String patientID, String appointmentID, String appointmentType);
  String swapAppointment (String patientID, String newAppointmentID, String newAppointmentType, String oldAppointmentID, String oldAppointmentType);
  void shutdown ();
} // interface ServerObjectInterfaceOperations
