package ServerObjectInterfaceApp;


/**
* ServerObjectInterfaceApp/ServerObjectInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerObjectInterface.idl
* Tuesday, April 9, 2024 10:22:40 o'clock AM EDT
*/

public abstract class ServerObjectInterfacePOA extends org.omg.PortableServer.Servant
 implements ServerObjectInterfaceApp.ServerObjectInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addAppointment", new java.lang.Integer (0));
    _methods.put ("removeAppointment", new java.lang.Integer (1));
    _methods.put ("listAppointmentAvailability", new java.lang.Integer (2));
    _methods.put ("bookAppointment", new java.lang.Integer (3));
    _methods.put ("getAppointmentSchedule", new java.lang.Integer (4));
    _methods.put ("cancelAppointment", new java.lang.Integer (5));
    _methods.put ("swapAppointment", new java.lang.Integer (6));
    _methods.put ("shutdown", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  /**
          * Only admin
          */
       case 0:  // ServerObjectInterfaceApp/ServerObjectInterface/addAppointment
       {
    	 String userID = in.read_string ();
    	 String appointmentID = in.read_string ();
         String appointmentType = in.read_string ();
         int bookingCapacity = in.read_long ();
         String $result = null;
         $result = this.addAppointment (userID, appointmentID, appointmentType, bookingCapacity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // ServerObjectInterfaceApp/ServerObjectInterface/removeAppointment
       {
    	 String userID = in.read_string ();
    	 String appointmentID = in.read_string ();
         String appointmentType = in.read_string ();
         String $result = null;
         $result = this.removeAppointment (userID, appointmentID, appointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ServerObjectInterfaceApp/ServerObjectInterface/listAppointmentAvailability
       {
    	 String userID = in.read_string ();
    	 String appointmentType = in.read_string ();
         String $result = null;
         $result = this.listAppointmentAvailability (userID, appointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  /**
          * Both admin and patient
          */
       case 3:  // ServerObjectInterfaceApp/ServerObjectInterface/bookAppointment
       {
         String patientID = in.read_string ();
         String appointmentID = in.read_string ();
         String appointmentType = in.read_string ();
         String $result = null;
         $result = this.bookAppointment (patientID, appointmentID, appointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // ServerObjectInterfaceApp/ServerObjectInterface/getAppointmentSchedule
       {
         String patientID = in.read_string ();
         String $result = null;
         $result = this.getAppointmentSchedule (patientID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // ServerObjectInterfaceApp/ServerObjectInterface/cancelAppointment
       {
         String patientID = in.read_string ();
         String appointmentID = in.read_string ();
         String appointmentType = in.read_string ();
         String $result = null;
         $result = this.cancelAppointment (patientID, appointmentID, appointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // ServerObjectInterfaceApp/ServerObjectInterface/swapAppointment
       {
         String patientID = in.read_string ();
         String newAppointmentID = in.read_string ();
         String newAppointmentType = in.read_string ();
         String oldAppointmentID = in.read_string ();
         String oldAppointmentType = in.read_string ();
         String $result = null;
         $result = this.swapAppointment (patientID, newAppointmentID, newAppointmentType, oldAppointmentID, oldAppointmentType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // ServerObjectInterfaceApp/ServerObjectInterface/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ServerObjectInterfaceApp/ServerObjectInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServerObjectInterface _this() 
  {
    return ServerObjectInterfaceHelper.narrow(
    super._this_object());
  }

  public ServerObjectInterface _this(org.omg.CORBA.ORB orb) 
  {
    return ServerObjectInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class ServerObjectInterfacePOA
